### ISSUE TITLE
DynamicNotebook looks weird on other distros

### ISSUE THREAD

**Issue by Allen-B1** [elementary/granite#104]
The DynamicNotebook has lines around the close button and the add tab button

![screenshot-notebook](https://user-images.githubusercontent.com/10786508/30675842-80ef9534-9e48-11e7-8de5-1957461eb835.png)

**Comment by Philip-Scott** [comment]
I've uploaded your screenshot from your dropbox to here. In the future, try to drag and drop a file to the text editor instead of linking externally :) Just in case you move your file

**Comment by matzipan** [comment]
Is this a granite issue? Or an issue with that theme's stylesheet?

**Comment by danrabbit** [comment]
We could probably be using flat class here and setting valign on that add button
