### ISSUE TITLE
Options no longer recognized 

### ISSUE THREAD

**Issue by jeremypw** [elementary/granite#107]
Passing local options to Granite Applications no longer works. Only Gtk options like -h are recognised.  The local options are shown with -h but are no longer functional, resulting in an "option not recognised" error when launching from a terminal.  Application functions that use these options, such as Files when launching Terminal no longer work.

This may be related to https://github.com/elementary/granite/commit/ab03e78349fb0e62fc4c17e43c6a4052dec9cf48

Essentially, unrecognised options are no longer ignored and running the app fails rather than passing the options to the instance to handle.

**Comment by tatsujb** [comment]
clearly this has not been fixed. also missing `-T` why not just use gnome-terminal and call it a day. this is really annoying and in a OS that's supposed to be easy-to use you end up having to do a lot of configuration to get rid of the default terminal.

**Comment by jeremypw** [comment]
Could you indicate an example of this not working?  It seems to be working OK for me as far as I have tested. 

The other two issues need separate reports I am afraid.

**Comment by tatsujb** [comment]
thought this fixed -e  as well you can close it again.
