### ISSUE TITLE
DynamicNotebook: Three Finger Tap to close tab re-opens one

### ISSUE THREAD

**Issue by Philip-Scott** [elementary/granite#109]
Tapping with three fingers (middle click) on a tab closes it, but also re-opens a previously closed tab

![peek 2017-09-29 07-26](https://user-images.githubusercontent.com/10786508/31015814-964dcf22-a4e7-11e7-8aec-87aed8e23878.gif)

This is a regression caused by: https://github.com/elementary/granite/commit/a3c083e53a38fb94e687a329673118ca125d7bc6

**Comment by danrabbit** [comment]
I can't confirm this in the demo, but I can can in both Scratch and Files

**Comment by Philip-Scott** [comment]
Looks like it's because the demo doesn't have the close history :thinking:
