### ISSUE TITLE
Granite demo crashes with undefined symbol

### ISSUE THREAD

**Issue by danrabbit** [elementary/granite#127]
Only happens with packaged version not run from source: 
`granite-demo: symbol lookup error: granite-demo: undefined symbol: granite_widgets_overlay_bar_set_label`

**Comment by davidmhewitt** [comment]
Can confirm this. But also, interestingly, after installing (not upgrading) `granite-demo`. The issue goes away.

Seems like the `granite-demo` we have left on our systems after the granite upgrade is still built against 0.4.

**Comment by danrabbit** [comment]
Yup, can confirm!

**Comment by codygarver** [comment]
You probably had leftover files on your system from compiling from source in the past, I can't reproduce this. Especially since it sounds like @davidmhewitt didn't have `granite-demo` package installed in the first place, so there was no way for it to get upgraded.
