### ISSUE TITLE
Can't initialize dynamic notebook tab as pinned

### ISSUE THREAD

**Issue by alcinnz** [elementary/granite#131]
In the attached program, the tab should show just it's icon whereas currently the label is also shown. 

I'll be interested in knowing whether it's Granite which is wrong or said program. 

[pinning-test.vala.txt](https://github.com/elementary/granite/files/1465061/pinning-test.vala.txt)

**Comment by tintou** [comment]
You need to enable pinning feature in the DynamicNotebook
`tabs.allow_pinning = true;`

It seems that you can't set the the `pinned` property of Granite.Widgets.Tab before adding it to the notebook so you have to do it after `tabs.insert_tab(tab, -1);`

**Comment by danrabbit** [comment]
Closing since we removed DynamicNotebook in favor of Hdy.Tabbar
