### ISSUE TITLE
MessageDialog: add a property for overlay icon

### ISSUE THREAD

**Issue by danrabbit** [elementary/granite#136]
There's several dialogs that overlay a small icon in the bottom right corner (like the Agent dialogs). It would be nice if we provided an easy way to do that in Granite.MessageDialog

**Comment by cassidyjames** [comment]
This could allow some nicer things in https://github.com/elementary/switchboard-plug-bluetooth/pull/50 without having to drop all the way back to a Gtk.Dialog.
