### ISSUE TITLE
Launchpad daily build fails: needs to update the symbols

### ISSUE THREAD

**Issue by khurshid-alam** [elementary/granite#139]
Granite in elementary daily build ppa is failing due to extra symbols. Build-log: https://launchpadlibrarian.net/353374083/buildlog_ubuntu-bionic-amd64.granite_0.5+r1151+pkg90~daily~ubuntu18.04.1_BUILDING.txt.gz

Please update the symbol files.

**Comment by danrabbit** [comment]
Closing since Granite is currently building in daily
