### ISSUE TITLE
Remove cmake/ParseArguments.cmake

### ISSUE THREAD

**Issue by yangfl** [elementary/granite#149]
Hi elementary group,

I see `cmake/ParseArguments.cmake` in the repo may be obsolete.

According to https://cmake.org/Wiki/CMakeMacroParseArguments , "If you are using CMake 2.8.3 or newer please use the CMakeParseArguments macro provided by the default CMake installation instead of the code below." Since your CMakeLists.txt specifies `cmake_minimum_required (VERSION 2.8)`, there's no need to such file any more.

Please consider remove it (and probably more like this).

Source: https://bugs.debian.org/873094#45

**Comment by tintou** [comment]
Hi @yangfl,
Some of our projects already made the change but we are working on switching to the Meson Build System so don't bother make the switch :slightly_smiling_face: 
See https://medium.com/elementaryos/all-aboard-the-meson-future-hype-train-2b6c478b6b9e for more information.

**Comment by tintou** [comment]
But the debian review there is quite useful
