### ISSUE TITLE
Add light / dark theme switch to demo

### ISSUE THREAD

**Issue by peteruithoven** [elementary/granite#151]
To test and demo the dark themed granite components it would be helpfull if we could switch the granite-demo between light and dark. 
Maybe we could add a simple toggle button to the headerbar, like Quickdocs:
![screenshot from 2018-02-10 10 45 40](https://user-images.githubusercontent.com/523210/36060745-ab884986-0e4f-11e8-8999-0c64ed08fea3.png)

**Comment by danrabbit** [comment]
Fixed in #152
