### ISSUE TITLE
Please consider fixing deprecated code

### ISSUE THREAD

**Issue by yangfl** [elementary/granite#159]
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=873094#71

There are tons of depreciation warnings in the latest code. Please consider fixing them.

An example warning log is attached.

[warnings.txt](https://github.com/elementary/granite/files/1766292/warnings.txt)

**Comment by tintou** [comment]
@yangfl There is nothing we can do about the deprecation warnings in the .c files as they are generated from the vala file. most of the time it's just deprecation from things that we declare as deprecated by ourself.
Basically if some function is marked as deprecated in C it will also be the case in Vala so you can safely remove the -Wdeprecated-declarations

**Comment by Exalm** [comment]
Some deprecations in that log are actual deprecations though. However, some of them don't have replacements and cannot be easily fixed, like `Gtk.Dialog.get_action_area()`/`gtk_dialog_get_action_area()`.

**Comment by danrabbit** [comment]
afaict we've fixed deprecations in the Gtk4 port, so closing as fixed
