### ISSUE TITLE
SimpleCommand doesn't close pipes on exit

### ISSUE THREAD

**Issue by bleakgrey** [elementary/granite#174]
https://github.com/elementary/granite/blob/0cb393b2d85da5d8d3ed3e3c96c6bb5d17ca598a/lib/Services/SimpleCommand.vala#L108

This part should probably look like this:
```
        ChildWatch.add(pid, (pid, exit) => {
            error_out.shutdown (false);
            out_make.shutdown (false);
            done(exit);
        });
```

Current behavior leads to "Too many opened files" error if one runs SimpleCommand over and over again as the pipes get shut down only when the process is closed:
![screenshot from 2018-05-02 20 33 29](https://user-images.githubusercontent.com/20158357/39539382-1e7daff2-4e48-11e8-8b4d-61c81f66de0d.png)

 This can be seen using `lsof -p APP_PID_HERE`:
![screenshot from 2018-05-02 20 24 02](https://user-images.githubusercontent.com/20158357/39538864-d8ed502e-4e46-11e8-9a3c-3c178d1c7e8d.png)

**Comment by danrabbit** [comment]
Closing because SimpleCommand has been deprecated
