### ISSUE TITLE
AppChooserWidget

### ISSUE THREAD

**Issue by danrabbit** [elementary/granite#198]
It seems like there is a demand for an alternative to the Gtk.AppChooserWidget and also maybe Gtk.AppChooserDialog.

Right now we're carrying a custom widget used in a popover in several Switchboard plugs (apps, security & privacy, parental controls) and it seems like there is demand to replace this dialog in Files since the Gtk.AppChooserDialog has some funny styling decisions with regards to the searchbar.

Something to ask is if maybe we should only do a full dialog and enforce that it's always a dialog and not use a popover or other embeds?

A solution here should:
* Probably have an API similar to https://valadoc.org/gtk+-3.0/Gtk.AppChooserDialog.html
* Provide a filter/search
* Handle what to do when there are no suggested apps for a provided content type

Another question: The app chooser in startup apps allows you to add a custom Terminal command. Is that a feature that might be useful in other contexts? Should we accommodate that as part of the design of this widget or is that too special case?

**Comment by SixFingeredAmish** [comment]
>The app chooser in startup apps allows you to add a custom Terminal command. Is that a feature that might be useful in other contexts? Should we accommodate that as part of the design of this widget or is that too special case?

I think that is too special of a case

**Comment by peteruithoven** [comment]
What if we generalize this a little bit into a filterable list thing? This way it could also be used for: 
![screenshot from 2018-10-12 19 19 00](https://user-images.githubusercontent.com/523210/46883950-bf2ffa00-ce53-11e8-95dc-9572f660eba8.png)

And fix: https://github.com/elementary/switchboard-plug-locale/issues/70

**Comment by SixFingeredAmish** [comment]
Great idea! But probably should be launched with a Filter icon, not a plus sign

**Comment by tintou** [comment]
The AppChooser widget won't make sense in the Flatpak world

**Comment by peteruithoven** [comment]
@tintou could you clarify? Why wouldn't we want to be able to select apps?

**Comment by tintou** [comment]
@peteruithoven in a flatpak environment a flatpak has no way to access any other installed application, the right way is to ask the portal "I want to open this `application/pdf`" and then the portal gives the choice (if there is a choice) to the user

**Comment by danrabbit** [comment]
I'm going to close this since we have an app chooser portal WIP in elementary/portals
