### ISSUE TITLE
Update translation files

### ISSUE THREAD

**Issue by ryonakano** [elementary/granite#199]
![2018-07-27 10 40 17](https://user-images.githubusercontent.com/26003928/43296982-9083d4e4-9189-11e8-94e0-a2e00ac32af0.png)

Because "Open in a New Window" is displayed as untranslated.

**Comment by danrabbit** [comment]
Should be fixed in b0389592fc81ac940b26b60522a0e091746f22e9

**Comment by ryonakano** [comment]
Thank you!
