### ISSUE TITLE
MessageDialog: one liner for creating, showing and closing the dialog

### ISSUE THREAD

**Issue by donadigo** [elementary/granite#204]
We should probably provide static a method like "MessageDialog.show_default ()` for easy error message embedding into the code. I've been almost always using the same code snippet and I wish it would just be in the class itself:

```
var dialog = new Granite.MessageDialog (...)
dialog.run ();
dialog.destroy ();
```

**Comment by danrabbit** [comment]
Going to close this since `run ()` has been removed from Gtk.Dialog so now what we do is connect to `response` and use `show` or `present`
