### ISSUE TITLE
Untranslated string

### ISSUE THREAD

**Issue by Djaler** [elementary/granite#206]
"Open in a New Window" string in DynamicNotebook is untranslated
![image](https://user-images.githubusercontent.com/7964583/44311581-a1658c00-a3f2-11e8-942b-99d3386b7342.png)

**Comment by ryonakano** [comment]
@Djaler I think you have to review and re-save the Russian translation of this string at https://l10n.elementary.io/translate/desktop/granite/ru/?checksum=c1138fe472474a37#nearby

**Comment by ryonakano** [comment]
![screenshot 2018-11-08 23 34 18](https://user-images.githubusercontent.com/26003928/48205112-f04a0e80-e3ae-11e8-96b3-004c26aed99f.png)

@Djaler Should be fixed now

**Comment by Djaler** [comment]
Yeah
