### ISSUE TITLE
Please avoid using cmake/ParseArguments.cmake

### ISSUE THREAD

**Issue by hosiet** [elementary/granite#209]
According to https://cmake.org/Wiki/CMakeMacroParseArguments , this file has long been obsoleted and replaced by [CMakeParseArguments](http://www.cmake.org/cmake/help/v2.8.9/cmake.html#module:CMakeParseArguments) macro provided by the default CMake installation.

Using `CMakeParseArguments` to replace `ParseArguments` is rather straightforward and simple. Please consider making the replacement so that we do not have to depend on the obsoleted and unmaintained code. Thanks!

**Comment by tintou** [comment]
We're now using meson
