### ISSUE TITLE
AyncImage memory leak

### ISSUE THREAD

**Issue by peteruithoven** [elementary/granite#223]
On Juno when installing libreoffice, viewing it's icons in the Applications menu causes Wingpanel's memory usage to go from 37MB to 200MB. 

Reproduce:
1. Comment our https://github.com/elementary/granite/blob/master/lib/Widgets/AsyncImage.vala#L333-L337 (ruling out other potential causes.)
2. Complile & install Granite
3. Compile & install Applications menu
1. Install libreoffice
2. Restart wingpanel (`$ killall wingpanel`)
2. View wingpanel memory usage. Should be around 37MB.
3. Open Applications menu
4. Visit Offie category
5. View wingpanel memory usage. Its suddenly at 200MB+.

After replacing `load_icon_async` with `load_icon` ([line](https://github.com/elementary/granite/blob/master/lib/Widgets/AsyncImage.vala#L330)) memory tops at around 62MB.

Relevant Applications menu issue: https://github.com/elementary/applications-menu/issues/117

Gtk gtk_icon_info_load_icon_async function:
https://gitlab.gnome.org/GNOME/gtk/blob/master/gtk/gtkicontheme.c#L3903-3931
I haven't found a relevant issue at: https://gitlab.gnome.org/GNOME/gtk/issues

**Comment by peteruithoven** [comment]
Instead of using `load_icon` commenting out the contents of the `update` function also seems to solve the issue...

**Comment by peteruithoven** [comment]
It's easy to reproduce by running the following script made by @donadigo:

```
static bool use_async = true;

public static int main (string[] args) {
    Gtk.init (ref args);
    var theme = Gtk.IconTheme.get_default ();

    List<unowned string> icons = theme.list_icons (null);
    var infos = new List<Gtk.IconInfo> ();
    foreach (string icon in icons) {
        infos.append (theme.lookup_icon (icon, 64, 0));
    }

    var pixbufs = new List<Gdk.Pixbuf> ();
    if (use_async) {
        foreach (unowned Gtk.IconInfo info in infos) {
            info.load_icon_async.begin (null, (obj, res) => {
                var pix = info.load_icon_async.end (res);
                pixbufs.append (pix);
                print (pixbufs.length ().to_string () + "\n");
            });
        }
    } else {
        foreach (unowned Gtk.IconInfo info in infos) {
            pixbufs.append(info.load_icon ());
            print (pixbufs.length ().to_string () + "\n");
        }
    }

    Gtk.main ();
    return 0;
}
```

Compile & run:
```
valac --pkg gtk+-3.0 test.vala
./test
```
See difference between memory usage when toggling: `use_async`

**Comment by peteruithoven** [comment]
@donadigo Opened an issue for GTK:
https://gitlab.gnome.org/GNOME/gtk/issues/1420

**Comment by ryonakano** [comment]
I can no longer reproducible this issue on Odin Daily, closing.
