### ISSUE TITLE
Contrasting color util

### ISSUE THREAD

**Issue by cassidyjames** [elementary/granite#244]
There are times when an app might want to get a contrasting color, i.e. white or black, in order to overlay onto a dynamically-colored background. For example, I use [a few utilities for this in Palette](https://github.com/cassidyjames/palette/blob/395103b1cd7735782a332c88f37857b8635137c8/src/Widgets/ColorButton.vala#L106), as demonstrated with the foreground text color here: ![screenshot](https://raw.githubusercontent.com/cassidyjames/palette/master/data/screenshots/screenshot-grape-const.png)

This could also be used for saner defaults for foreground colors in branded headerbars, preventing unreadable dark gray text on darker brand colors.

**Comment by peteruithoven** [comment]
This would also help with: 
- https://github.com/elementary/files/issues/937
- https://github.com/elementary/switchboard-plug-display/blob/de6bc33bb469fed25c7cc94c0e23c33a7958cd42/src/Widgets/DisplaysOverlay.vala#L36-L53
