### ISSUE TITLE
Programmatically generate fallback avatars

### ISSUE THREAD

**Issue by cassidyjames** [elementary/granite#245]
This is something I feel like we've discussed several times but apparently haven't documented anywhere. Instead of just having an icon, we should programmatically generate some sort of distinct avatar for fallbacks whenever possible, i.e. by using initials or the first character of a provided email address, plus a color generated from a hash.

Google does this across their properties, so the Android implementation for Material Design is likely open source.

**Comment by danrabbit** [comment]
This applies to system accounts and probably social accounts as well as email, so I think we just want the API to be "a string" and split it at spaces such that you get results like:

foobar = "F"
foo@bar.com = "F"
Foo Bar = "FB"

**Comment by cassidyjames** [comment]
and if for some reason we can't generate something (i.e. an unexpected character or null?) we can always just fall back to the existing fallback.
