### ISSUE TITLE
Same label for ItemDescription.FILES and ItemDescription.OTHER

### ISSUE THREAD

**Issue by jeremypw** [elementary/granite#247]
In StorageBar, if a block is added with the ItemDescription.OTHER it appears with same label and with the same color as ItemDescription.FILES and therefore cannot be usefully employed.

There is a need for a block that shows storage space that is inaccessible, because some filesystems, including ext4, may reserve some space for use be root and is therefore inaccessible to the normal user.  The 'OTHER' description could be used for this were it to be given a distinguishing name and color.

**Comment by danrabbit** [comment]
Closing since StorageBar was moved to Files
