### ISSUE TITLE
DateTime: using in other DEs cause crashes

### ISSUE THREAD

**Issue by cjfloss** [elementary/granite#249]
Using `Granite.Datetime.get_relative_datetime` on systems that don't have wingpanel installed crashes applications.

Related: https://github.com/alainm23/planner/issues/5

**Comment by decathorpe** [comment]
My https://github.com/elementary/granite/pull/242 would fix this. But it doesn't look like it will be accepted, leaving users of granite everywhere except on Pantheon out in the rain.

**Comment by memnoth** [comment]
Check out the referenced PR above. That's not a perfect solution at all, but anyone who wants granite can make workaround just like that.
