### ISSUE TITLE
Duplicate tab when pressing Ctrl while dragging

### ISSUE THREAD

**Issue by peteruithoven** [elementary/granite#258]
Some browsers like Firefox support duplicating a tab by holding <kbd>Ctrl</kbd> while dragging:
![screen record from 2019-01-25 23 59 56](https://user-images.githubusercontent.com/523210/51777523-c5de3680-20fd-11e9-9890-72e0d7d835a4.gif)
(I'm using the [firefox-elementary-theme ](https://github.com/harveycabaguio/firefox-elementary-theme))

Would this be interesting for Granite's DynamicNotebook? I'd love to be able to do this in apps like Files and Terminal.

**Comment by danrabbit** [comment]
Closing since we removed DynamicNotebook in favor of Hdy.Tabbar
