### ISSUE TITLE
No way to unselect all items in SourceList

### ISSUE THREAD

**Issue by TheNightmanCodeth** [elementary/granite#264]
I'm working on a project which would benefit from having this functionality implemented. I'm in the process of looking around in the `SourceList` code and implementing this myself, but I thought I'd open an issue to get some feedback before submitting a PR.

In my project I would like to have a paned view with a source list. The window should display a certain view alongside the `SourceList` before an item is even selected in the list, and a different one after the user picks an item. This would require a way to either: 

- Set a property on the `SourceList` to have no item selected by default
or
- Call a method to deselect all `TreeViewSelections` in the list

Is there any reason that either or both of these should not be implemented? Or, more importantly, is there a way to do this already that I'm missing?

**Comment by danrabbit** [comment]
Closing since SourceList was removed during the Gtk4 port
