### ISSUE TITLE
5.2.3: issue with granite-update-po target

### ISSUE THREAD

**Issue by kloczek** [elementary/granite#283]
<pre>[tkloczko@domek granite-5.2.3]$ /usr/bin/ninja -v -j4 -C x86_64-redhat-linux-gnu -t targets
granite-pot: phony
granite-gmo: phony
granite-update-po: phony
test: phony
benchmark: phony
install: phony
dist: phony
scan-build: phony
uninstall: phony
clean: phony
build.ninja: REGENERATE_BUILD
reconfigure: REGENERATE_BUILD
</pre>

<pre>[tkloczko@domek granite-5.2.3]$ /usr/bin/ninja -v -C x86_64-redhat-linux-gnu granite-update-po
ninja: Entering directory `x86_64-redhat-linux-gnu&apos;
[0/1] /usr/bin/meson --internal commandrunner /home/tkloczko/rpmbuild/BUILD/granite-5.2.3 /home/tkloczko/rpmbuild/BUILD/granite-5.2.3/x86_64-redhat-linux-gnu po /usr/bin/meson /usr/bin/meson --internal gettext update_po --pkgname=granite --extra-args=--flag=g_strdup_printf:1:c-format@@--add-comments@@--flag=g_markup_printf_escaped:1:c-format@@--flag=g_printf:1:c-format@@--flag=g_print:1:c-format@@--flag=NC_:2:pass-c-format@@--flag=C_:2:pass-c-format@@--flag=g_set_error:4:c-format@@--flag=g_error_new:3:c-format@@--keyword=g_dpgettext2:2c,3@@--flag=g_fprintf:2:c-format@@--keyword=NC_:1c,2@@--flag=g_printerr:1:c-format@@--from-code=UTF-8@@--keyword=_@@--flag=g_log:3:c-format@@--flag=g_string_printf:2:c-format@@--flag=N_:1:pass-c-format@@--flag=g_snprintf:3:c-format@@--keyword=N_@@--keyword=C_:1c,2@@--keyword=g_dcgettext:2@@--flag=g_dngettext:2:pass-c-format@@--flag=g_string_append_printf:2:c-format@@--keyword=g_dngettext:2,3@@--directory=/home/tkloczko/rpmbuild/BUILD/granite-5.2.3@@--flag=g_sprintf:2:c-format
Could not find file POTFILES in /home/tkloczko/rpmbuild/BUILD/granite-5.2.3/po
FAILED: meson-granite-update-po 
/usr/bin/meson --internal commandrunner /home/tkloczko/rpmbuild/BUILD/granite-5.2.3 /home/tkloczko/rpmbuild/BUILD/granite-5.2.3/x86_64-redhat-linux-gnu po /usr/bin/meson /usr/bin/meson --internal gettext update_po --pkgname=granite --extra-args=--flag=g_strdup_printf:1:c-format@@--add-comments@@--flag=g_markup_printf_escaped:1:c-format@@--flag=g_printf:1:c-format@@--flag=g_print:1:c-format@@--flag=NC_:2:pass-c-format@@--flag=C_:2:pass-c-format@@--flag=g_set_error:4:c-format@@--flag=g_error_new:3:c-format@@--keyword=g_dpgettext2:2c,3@@--flag=g_fprintf:2:c-format@@--keyword=NC_:1c,2@@--flag=g_printerr:1:c-format@@--from-code=UTF-8@@--keyword=_@@--flag=g_log:3:c-format@@--flag=g_string_printf:2:c-format@@--flag=N_:1:pass-c-format@@--flag=g_snprintf:3:c-format@@--keyword=N_@@--keyword=C_:1c,2@@--keyword=g_dcgettext:2@@--flag=g_dngettext:2:pass-c-format@@--flag=g_string_append_printf:2:c-format@@--keyword=g_dngettext:2,3@@--directory=/home/tkloczko/rpmbuild/BUILD/granite-5.2.3@@--flag=g_sprintf:2:c-format
ninja: build stopped: subcommand failed.
</pre>

<pre>[tkloczko@domek granite-5.2.3]$ ls po/
aa.po   av.po  bo.po   cu.po     en_CA.po  fo.po        gv.po  ia.po  ja.po  ko.po  LINGUAS      mi.po  nb.po  oc.po     pt.po   sd.po   sq.po  th.po  ty.po  xh.po
ab.po   ay.po  br.po   cv.po     en_GB.po  fr_CA.po     ha.po  id.po  jv.po  kr.po  li.po        mk.po  nd.po  oj.po     qu.po   se.po   sr.po  ti.po  ug.po  yi.po
ae.po   az.po  bs.po   cy.po     eo.po     fr.po        he.po  ie.po  ka.po  ks.po  ln.po        ml.po  ne.po  om.po     rm.po   sg.po   ss.po  tk.po  uk.po  yo.po
af.po   ba.po  ca.po   da.po     es.po     fy.po        hi.po  ig.po  kg.po  ku.po  lo.po        mn.po  ng.po  or.po     rn.po   si.po   st.po  tl.po  ur.po  za.po
ak.po   be.po  ce.po   de.po     et.po     ga.po        ho.po  ii.po  ki.po  kv.po  lt.po        mo.po  nl.po  os.po     ro.po   sk.po   su.po  tn.po  uz.po  zh_CN.po
am.po   bg.po  ch.po   dv.po     eu.po     gd.po        hr.po  ik.po  kj.po  kw.po  lu.po        mr.po  nn.po  pa.po     rue.po  sl.po   sv.po  to.po  ve.po  zh_HK.po
an.po   bh.po  ckb.po  dz.po     fa.po     gl.po        ht.po  io.po  kk.po  ky.po  lv.po        ms.po  no.po  pi.po     ru.po   sma.po  sw.po  tr.po  vi.po  zh.po
ar.po   bi.po  co.po   ee.po     ff.po     gn.po        hu.po  is.po  kl.po  la.po  meson.build  mt.po  nr.po  pl.po     rw.po   sm.po   ta.po  ts.po  vo.po  zh_TW.po
as.po   bm.po  cr.po   el.po     fi.po     granite.pot  hy.po  it.po  km.po  lb.po  mg.po        my.po  nv.po  ps.po     sa.po   sn.po   te.po  tt.po  wa.po  zu.po
ast.po  bn.po  cs.po   en_AU.po  fj.po     gu.po        hz.po  iu.po  kn.po  lg.po  mh.po        na.po  ny.po  pt_BR.po  sc.po   so.po   tg.po  tw.po  wo.po
</pre>

So indeed po/POTFILES is missing.

**Comment by worldofpeace** [comment]
It seems https://github.com/elementary/granite/commit/e11a7b1561ef2361da4bfbbe917209da36b0b317#diff-4b342998356e4e784df645bd2edc564b added this file so this has been fixed in `5.2.4`

**Comment by danrabbit** [comment]
Closing since 5.2.4 is released
