### ISSUE TITLE
Provide the missing bits from libunity

### ISSUE THREAD

**Issue by tintou** [elementary/granite#287]
We are relying on libunity in a few places and the library is over-complicated and using outdated dependencies, it might be the right time to provide our alternative to it:

Alternative API:
```vala
namespace Granite.Application {
    public static bool set_badge (int64 count) throws GLib.Error;
    public static bool set_badge_visible (bool visible) throws GLib.Error;
    public static bool set_progress (double progress) throws GLib.Error;
    public static bool set_progress_visible (bool visible) throws GLib.Error;
    public static bool set_dynamic_menu (GLib.Menu menu) throws GLib.Error;
}
```
This API would internally use the `GLib.Application.get_default ().application_id`

The `dynamic menu` one might be questionable : Only Switchboard is using it and it's not persistent.

**Comment by danrabbit** [comment]
Files is using the dynamic quicklist also, but yeah the fact that it isn't persistent makes it of pretty questionable utility to me. I think we'd probably be fine to lose it
