### ISSUE TITLE
Some settings pane title look like they're editable

### ISSUE THREAD

**Issue by D0J0P** [elementary/granite#308]
This seems to work for Bluetooth, Language & Region, Security & Privacy, and About, but NOT for Notifications, Network, and Sharing. 
![Screenshot from 2019-07-26 19 50 57](https://user-images.githubusercontent.com/19495660/61986821-deada300-afdf-11e9-9acd-90b9eb20789e.png)

They look like they're editable. They can also be double-clicked to highlight so you can copy it. 

This is similar to [#1049](https://github.com/elementary/appcenter/issues/1049) where text looks like they can be edited, but on double-clicking, you can highlight them to copy the text if you want to paste it somewhere. That definitely works in AppCenter for names of apps and authors, but I'm not sure how that could work for settings pane like "Bluetooth" and so on, when people will just type "bluetooth".

**Comment by danrabbit** [comment]
Closing as a design conflict since making these labels selectable is intentional.

Mentioning @elementary/ux in case anyone has further thoughts

**Comment by cassidyjames** [comment]
I guess my thought is… why are they selectable? :joy: I know [we recommend that](https://elementary.io/docs/human-interface-guidelines#dialogs) for dialogs, but I think that's going to typically be more copy than in a setting title.

**Comment by D0J0P** [comment]
That's fine if it's intentional. Though I do agree with Cassidy as to asking why it's intentional when it's probably easier to type "Bluetooth" than copying and pasting the system pane title when the name isn't branded, but is a noun. 

If there is anything to fix though, it's Notifications, Network and Sharing panes not being selectable like the others are.
