### ISSUE TITLE
Add the middle-split window as a special type of Window

### ISSUE THREAD

**Issue by aggalex** [elementary/granite#313]
Many apps are already using it, and adding it to granite will definitely make it more accessible to developers and more readable (by hiding the code of just constructing the window into eg. a class that inherits from Gtk.Window)

## Examples of apps using it:
- [Cyfrif](https://appcenter.elementary.io/com.github.aimproxy.cyfrif)
- [Ion Color Generator](https://appcenter.elementary.io/com.github.alainm23.ioncolorgenerator)
- [Harvey](https://appcenter.elementary.io/com.github.danrabbit.harvey.desktop)
- [Tasks](https://github.com/elementary/tasks)

**Comment by danrabbit** [comment]
As discussed on the associated pull request Hdy.Window is now available in elementary OS 6 and provides everything you need to make split headerbar windows easily
