### ISSUE TITLE
Toast.send_notification () should reset timeout

### ISSUE THREAD

**Issue by cassidyjames** [elementary/granite#320]
If you send a notification several times, it will still hide after the initial timeout

**Comment by Alecaddd** [comment]
It would be also great if we could change the default timeout per notification with this method.
eg. `Toast.send_notification (6000)`;

**Comment by cassidyjames** [comment]
@Alecaddd we've decided against that since it would lead to inconsistent timeouts across apps. Instead, we currently base the timeout length on whether or not there's an action to be performed. What's your use case for a significantly longer timeout?

**Comment by cassidyjames** [comment]
@Alecaddd we could also be smart and just… increase the timeout based on the length of the string? :thinking:
