### ISSUE TITLE
Provide libunity features

### ISSUE THREAD

**Issue by bilelmoussaoui** [elementary/granite#326]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

libunity depends on gnome-common & libdbusmenu and it's becoming more and more of a pain to maintain any usable builds without patching a lot of things :/

**Describe the solution you'd like**

elementary app developers could use Granite to directly communicate with the system by a DBus API without having to use libunity. As libunity is mostly dbus calls, it should be easy to implement those features here

**Existing work**

libunity? Geary also plans to remove libunity dependency in the future and just implement the dbus calls themselves

**Describe alternatives you've considered**

**Additional context**

As elementary is moving towards a sandboxed packaging world, removing libnuity will make the developers create their manifests pretty easily without having to deal with those old libraries.

**Comment by tintou** [comment]
Good news: it's already the case since [5.2.5](https://github.com/elementary/granite/releases/tag/5.2.5) ! (Note that only the badge and progress API is covered as we are not interested by the other features)

**Comment by bilelmoussaoui** [comment]
My bad, I should have checked the latest releases first. Thanks!
