### ISSUE TITLE
DynamicNotebook: Button highlights not cleared correctly

### ISSUE THREAD

**Issue by jlnr** [elementary/granite#331]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

When the "Add Tab" or "Close Tab" buttons receive a mouse-down event, they go into a highlighted state (light gray background in the screencast below).

When the user decides to cancel the action by dragging the mouse away from the button before releasing, this highlight is not cleared. Only clicking somewhere else in the window afterwards will clear it.

### To Reproduce
1. Open Terminal or Files with current granite master
2. Click on either the "X" for the current tab, or the "+" to the left of the tab bar
3. Drag the mouse away from the window
4. Release

### Expected behavior

Highlight is cleared as soon as I release the button

### Screenshots or screen recordings

![tab-button-bug](https://user-images.githubusercontent.com/70772/66702600-9ada5800-ed09-11e9-9c94-5e94a5c14f6e.gif)

## Platform Information

- [x] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

**Comment by Exalm** [comment]
FWIW, it also happens in Epiphany for new tab button, which isn't using DynamicNotebook. Not for close buttons though, but they are also not focusable.

**Comment by danrabbit** [comment]
Closing since we removed DynamicNotebook in favor of Hdy.Tabbar
