### ISSUE TITLE
libgranite.so lives in the wrong package

### ISSUE THREAD

**Issue by jmc-88** [elementary/granite#368]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
`libgranite.so` lives in the `libgranite-dev` package, though arguably it should live in the `libgranite5` package which actually provides the library.

### To Reproduce
```
$ dpkg-query -L libgranite-dev
/.
/usr
/usr/include
/usr/include/granite
/usr/include/granite/granite.h
/usr/include/granite/widgets-utils.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/granite.pc
/usr/share
/usr/share/doc
/usr/share/doc/libgranite-dev
/usr/share/doc/libgranite-dev/changelog.gz
/usr/share/doc/libgranite-dev/copyright
/usr/share/gir-1.0
/usr/share/gir-1.0/Granite-1.0.gir
/usr/share/vala
/usr/share/vala/vapi
/usr/share/vala/vapi/granite.deps
/usr/share/vala/vapi/granite.vapi
/usr/lib/x86_64-linux-gnu/libgranite.so

$ dpkg-query -L libgranite5
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libgranite.so.5.3.0
/usr/share
/usr/share/doc
/usr/share/doc/libgranite5
/usr/share/doc/libgranite5/changelog.gz
/usr/share/doc/libgranite5/copyright
/usr/lib/x86_64-linux-gnu/libgranite.so.5
```

### Expected behavior
`libgranite.so`, `libgranite.so.5`, and `libgranite.so.5.3.0` should be provided by the same package.

Note that `libgranite.so` and `libgranite.so.5` are merely symlink to the fully-qualified versioned library file `libgranite.so.5.3.0`.

## Platform Information
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

```
$ dpkg-query -W libgranite5 libgranite-dev
libgranite-dev	5.3.0+r1497+pkg112~ubuntu5.1.1
libgranite5:amd64	5.3.0+r1497+pkg112~ubuntu5.1.1
```

**Comment by ricotz** [comment]
Sorry, but your assumption is wrong and the way the files are separated is correct as is.

https://www.debian.org/doc/debian-policy/ch-sharedlibs.html#development-files
