### ISSUE TITLE
[DynamicNotebook]Clicking on current tab steals focus when TabBarBehaviour.SINGLE

### ISSUE THREAD

**Issue by jeremypw** [elementary/granite#377]
I have searched open and closed issues for duplicates.

See https://github.com/elementary/terminal/issues/494 for details of the effects of this issue.

### Expected behavior
TabBarBehaviour setting should not affect the focus.

## Platform Information
Hera daily.

**Comment by danrabbit** [comment]
Closing since we removed DynamicNotebook in favor of Hdy.Tabbar
