### ISSUE TITLE
Gear menu popover is too large

### ISSUE THREAD

**Issue by janxkoci** [elementary/granite#385]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
The gear menu popover is too large. I believe it is caused by the keyboard shortcut for showing sidebar - it is using the word `backslash` instead of the character `\` ("backslash" in my Czech locale translates into "zpětné lomítko", which is particularly long).

### To Reproduce
1. Open Code
2. Click on the gear icon on top right
3. There!

### Expected behavior
The popover used to be smaller, similar in size to the popover menu in Terminal. This could be achieved by using the character `\` instead of the word `backslash`.

### Screenshots or screen recordings

![Snímek z 2020-04-27 15-17-44](https://user-images.githubusercontent.com/19331850/80381891-e3babe00-88a1-11ea-9636-c3b194a6f815.png)

## Platform Information

![Snímek z 2020-04-27 16-12-58](https://user-images.githubusercontent.com/19331850/80381961-fa611500-88a1-11ea-98a0-662342a17926.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by janxkoci** [comment]
Huh, somehow I didn't see the notifications for this. I don't know of any better translation, the one present is a literal "back slash", as we use it too. However I always have to think about which slash is which, seeing the symbol would be easier for me (and I guess for others too).

**Comment by cassidyjames** [comment]
@janxkoci yep, that's what we went with: just showing the symbol. It seems more clear. Thanks for reporting this!
