### ISSUE TITLE
Expose accent color in Granite.Settings

### ISSUE THREAD

**Issue by cassidyjames** [elementary/granite#394]
Similar to https://github.com/elementary/granite/pull/319. Requires https://github.com/elementary/default-settings/issues/175.

**Comment by danrabbit** [comment]
Hm I’m not sure this is necessary. For apps, surely anything they want to do with accent color is CSS related right? And the greeter can read from dbus directly

**Comment by cassidyjames** [comment]
@danrabbit I am not sure how we plan for flatpaked apps to get the default accent color (i.e. if they're not overriding it). I guess… this would be handled somehow by the Flatpak Platform setting the right stylesheet? But I have no idea how that works. 

But if we tell developers to manually request a stylesheet, it would probably be good to request a stylesheet that matches the user's accent color preference unless the app has branding reasons to set their own accent color.

**Comment by Marukesu** [comment]
From what I understand, in X11, flatpak use the system xsettings to get the theme,  if it don't exist on the platform, Adwaita is used. But You can force a theme with the GTK.Settings Class in the application code.
