### ISSUE TITLE
Add `default-decoration` style class constant

### ISSUE THREAD

**Issue by cassidyjames** [elementary/granite#395]
I thought this might be a GTK thing but it looks like it's not defined by them or us. Since we use it and encourage devs to use it, we should define it as a constant.

**Comment by danrabbit** [comment]
Yeah Gtk uses it internally, but they don’t have a constant for it.

I kind of feel like it might be better to create a more semantic class name in case Gtk changes this upstream and it breaks all our styles.

**Comment by cassidyjames** [comment]
@danrabbit I don't feel that strongly, but how would it break for apps that are adding the style class via the constant? The nice thing about encouraging using a constant is that we can change it under the hood later if we want to track GTK, or just change it to something else later.
