### ISSUE TITLE
Exposing the Gtk.TreeView property enable_tree_lines to Granite.Widgets.SourceList

### ISSUE THREAD

**Issue by RippieUK** [elementary/granite#416]
## Feature
Could it be possible to expose the property `enable_tree_lines` in the Gtk.TreeView to the Granite.Widgets.SourceList? 

It would mean that i could do something like:
```
var source_list = new Granite.Widgets.SourceList ();
source_list.enable_tree_lines = true;
```

instead of 
```
var source_list = new Granite.Widgets.SourceList ();
((Gtk.TreeView) source_list.get_child ()).enable_tree_lines = true;
```

**More info**
This really came about because i spotted that property in the Gtk Inspector while I was in Code and it honestly made such a big difference to me. It made it visibly much easier to tell the difference between files in different folders.

David Hewitt kindly explained that perhaps there was a reason why the property was not exposed and that the correct thing to do would be to ask for it to be included into the SourceList widget.

**Comment by danrabbit** [comment]
Closing since SourceList was removed during the Gtk4 port
