### ISSUE TITLE
failed to build with turkish language

### ISSUE THREAD

**Issue by efectn** [elementary/granite#424]
I have this error on build package with Turkish:

```
value contains invalid characters: ınfo'
ninja: build stopped subcommand failed. HATA: build() içinde bir hata oluştu.

Çıkılıyor..: error making: X!s(func) string=0x55de058aeedo)

```
Because; The lowercase version of "I" is mentioned as "ı" in Turkish. This causes problems while creating the package. Please fix it...

**Comment by paledega** [comment]
you must run before build
`export LANG=en_US.UTF-8`

**Comment by paledega** [comment]
this is demo subdir issue
I sent pull request for adding disable options

https://github.com/elementary/granite/pull/423

**Comment by paledega** [comment]
I found a bug on g-ir-compiler
I created issue page. 

https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/356

**Comment by danrabbit** [comment]
It appears this is an issue in Vala which has been fixed: https://gitlab.gnome.org/GNOME/vala/-/issues/1067

Closing as "Out of Scope"
