### ISSUE TITLE
Granite dialog should inherit Gtk.Window instead of Gtk.Dialog

### ISSUE THREAD

**Issue by cassidyjames** [elementary/granite#443]
If we want to stop setting the thing that gets GTK dialog buttons out of headerbars, we need to not subclass Gtk.Dialog.

**Comment by danrabbit** [comment]
More specifically, we need to replace any of our usage of Gtk.Dialog in any of our apps. So we probably need to create a new Granite.Dialog that's a Gtk.Window subclass and then Granite.MessageDialog should subclass that
