### ISSUE TITLE
libgranite-dev causes package conflict between libgranite5 and libgranite6

### ISSUE THREAD

**Issue by ztefn** [elementary/granite#454]
## What Happened
I was installing updates when this error popped up:

```
dpkg: error processing archive /tmp/apt-dpkg-install-brElq0/08-libgranite6_5.5.0+r1759+pkg117~ubuntu5.1.7.1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libgranite.so.5.5.0', which is also in package libgranite5:amd64 5.5.0+r1759+pkg115~ubuntu5.1.5.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-brElq0/08-libgranite6_5.5.0+r1759+pkg117~ubuntu5.1.7.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
This seems to be caused by having the package **libgranite-dev** installed on the system (because I maintain [an app in AppCenter](https://appcenter.elementary.io/com.github.ztefn.haguichi/)). This package depends on libgranite6 which seems to come with libgranite.so.5.5.0, which is exactly the same file as libgranite5. And you cannot remove libgranite5 because all elementary apps depend on it...

## Expected Behavior
No conflicting packages.

## Steps to Reproduce
1. Try to install libgranite-dev or update the system when you already have
2. Profit

## Platform Information
elementary OS 5.1.7 Hera

**Comment by danrabbit** [comment]
Looks like Launchpad auto built stable granite with development packaging. Working on a fix. Sorry about that :grimacing:

**Comment by danrabbit** [comment]
Okay this should be fixed now. The build should complete in the next couple of minutes so an update should fix this within the next day

**Comment by kreativnix** [comment]
I wanted install today the Terminal of elementary os 6 and working down the todo list I got the error that granite6 is missing.
Unfortunately there is a conflict with the installed version 5 which I can not overcome.
I use Ubuntu 20.04 actally patched.
........
Run-time dependency granite found: NO (tried cmake)
meson.build:50:0: ERROR: Invalid version of dependency, need 'granite' ['>=6.1.0'] found '5.3.0'.
...

Hope you can help me.
Best regards
