### ISSUE TITLE
Non-popover modelbutton 

### ISSUE THREAD

**Issue by hanaral** [elementary/granite#478]
## Problem

As it stands apps like System Settings have lots of weirdly padded toggles on the ends of setting names and descriptions. Switches may be many times larger than tickboxes, but it is still more naturall in all cases of destkop UX to click on associated text. Users cannot currently do this outside popovers, which is also inconsistent _(imo)_ 

## Proposal

Despite tickboxes being pretty terrible UX, at least macOS has always had a huge selection box around the tickbox and its text which highlights when hovered.

Have a nicely padded 'bubble' around a model button when it isn't in a popover (I don't know if it can be smart like this, it may need a seperate widget)

This should allow settings switches to take up less space and be easier to align by orders of magnitude

Either this or do the same thing with checkboxes so that there is a clear distinction between popover UI and window UI

**Comment by danrabbit** [comment]
I'm having a hard time understanding what it is you're trying to report here. Please try to stick to only facts and avoid opinion statements. Is the problem you're having with a checkbox somewhere or with a switch?

Can you maybe describe what you think a model button is? I'm not sure how that's fitting into this report.

Can you maybe include a screenshot of the problem you're seeing?

**Comment by danrabbit** [comment]
Closing since there was no follow up
