### ISSUE TITLE
Increase required valac version?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/granite#492]
## What Happened

Can't compile fresh clone of master branch of Granite on elementary OS 5. I get these errors:
```
../lib/Widgets/SwitchModelButton.vala:65.9-65.19: error: The type name `var' could not be found
        unowned var description_style_context = description_label.get_style_context ();
        ^^^^^^^^^^^
../lib/Widgets/Utils.vala:298.5-298.15: error: The type name `var' could not be found
    unowned var gtk_settings = Gtk.Settings.get_default ();
    ^^^^^^^^^^^
```

While I got no warnings from meson's setup:
```
meson build --prefix=/usr
The Meson build system
Version: 0.49.2
Source dir: /home/peteruithoven/Projects/elementary/granite
Build dir: /home/peteruithoven/Projects/elementary/granite/build
Build type: native build
Project name: granite
Project version: 6.1.0
Native C compiler: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
Native Vala compiler: valac (valac 0.40.25)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Dependency gio-unix-2.0 found: YES 2.56.4
Dependency gee-0.8 found: YES 0.20.2
Dependency gio-2.0 found: YES 2.56.4
Dependency glib-2.0 found: YES 2.56.4
Dependency gobject-2.0 found: YES 2.56.4
Dependency gtk+-3.0 found: YES 3.22.30
Configuring Config.vala using configuration
Library m found: YES
Library posix found: YES
Program g-ir-compiler found: YES (/usr/bin/g-ir-compiler)
Program /home/peteruithoven/Projects/elementary/granite/meson/post_install.py found: YES (/home/peteruithoven/Projects/elementary/granite/meson/post_install.py)
Build targets in project: 10
Found ninja-1.8.2 at /usr/bin/ninja
```

## Expected Behavior

I'd get a clearer warning that my current setup isn't supported. 

According to @jeremypw the meson.build needs to be updated:
https://github.com/elementary/granite/pull/236#issuecomment-830609727
Probably specifically the valac version: 
https://github.com/elementary/granite/blob/master/meson.build#L8

I'm just not sure how to check from which version of the valac this `var` thing is supported. The [changelog](https://gitlab.gnome.org/GNOME/vala/-/blob/master/ChangeLog.pre-0-4) contains dates, not versoins. Or maybe it should just be set to the current version of valac that's included in elementary 6? 

## Steps to Reproduce

1. Clone Granite on elementary OS 5
2. Run: `meson build --prefix=/usr`
3. Run: `cd build`
4. Run: `ninja`

## Platform Information

elementary OS 5.1.7 Hera
Compiled from git

**Comment by jeremypw** [comment]
Yes, looking at the error message `unowned var` is not supported before (I think) Vala 0.48.
