### ISSUE TITLE
kdeconnect indicator not working on EOS 

### ISSUE THREAD

**Issue by Moondog8862** [elementary/granite#497]
Working on:
uname -rvio
5.4.0-51-generic #56~18.04.1-Ubuntu SMP Tue Oct 6 09:47:18 UTC 2020 x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/83641875/116989145-a4ebef00-acd1-11eb-941e-408654439aba.png)

## What Happened

On calling:
kdeconnect-indicator 

Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.

## Expected Behavior

Indicator does not appear in wingpanel

## Steps to Reproduce

1. kdeconnect-indicator

**Comment by cassidyjames** [comment]
1. elementary OS does not have application indicators.

2. This repository is for Granite, a development library, and does not have anything to do with Qt or KDE or the elementary OS Panel

3. The warnings listed look like unrelated warnings from the KDE indicator and should be reported to the maintainers of that indicator, but they're unrelated to the fact that elementary OS doesn't have application indicators.
