### ISSUE TITLE
Avatar Widget: DPI changes don't update the icon

### ISSUE THREAD

**Issue by Philip-Scott** [elementary/granite#50]
![screenshot from 2017-05-09 13 04 20](https://cloud.githubusercontent.com/assets/10786508/25865407/6d8b2912-34b8-11e7-9503-a797a2b437df.png)
![screenshot from 2017-05-09 13 07 30](https://cloud.githubusercontent.com/assets/10786508/25865421/78334eee-34b8-11e7-998c-5ea2f65cdfb0.png)

**Comment by danrabbit** [comment]
This can also be reproduced on the greeter

**Comment by davidmhewitt** [comment]
Fixed in #75
