### ISSUE TITLE
context-menu of a tab in DynamicNotebook is scrollable up with no end

### ISSUE THREAD

**Issue by gre0j** [elementary/granite#506]
## What Happened
In the latest Version: 4.5.0+r4521+pkg100-daily-ubuntu6.1 the context-menu is scrollable up to nowhere
 

## Expected Behavior
No scrolling or with end. 

## Steps to Reproduce
Go to settings > desktop and change the font-size to bigger.
Open a new tab and open the context-menu, there you can scroll up with no end.
![Bildschirmfoto von 2021-06-15 18 23 41](https://user-images.githubusercontent.com/23266409/122089674-4903a280-ce07-11eb-9665-4465ca806751.png)

 When you close the context-menu and open it again, then everything is fine. 
![Bildschirmfoto von 2021-06-15 18 28 53](https://user-images.githubusercontent.com/23266409/122090023-9f70e100-ce07-11eb-9913-1cfb3bb3ebc3.png)

## Platform Information

elementary OS 6 Early Access

**Comment by danrabbit** [comment]
Closing since we removed DynamicNotebook in favor of Hdy.Tabbar
