### ISSUE TITLE
[Granite.hypertextview] A textview that has basic autocorrect functionality

### ISSUE THREAD

**Issue by hanaral** [elementary/granite#509]
## Problem

Other platforms like iOS, macOS, Android(?) have a builtin method of providing some dictionary suggestions for unknown words in that keyboard/document language. elementary OS has no way of doing this apart from custom implementations, really only ever found in word processors or code editors - users have to go and look up the spelling of a word themselves if they are, for example, setting up a calendar event for their company

## Proposal

The hypertextview, if it is accepted, should also be given the ability to check dictionary spellings for words based on the user's keyboard language. To solve the performance issue, only text that has been changed could be analysed and have sanity checked for whether it is a normal word - essentially the same way that it checks for real hyperlinks.
Maybe it could be renamed to Granite.richtextview or smarttextview if necessary to imply that it's not just for links

This would probably give developers more of a reason to use it than just for hyperlinks

## Prior Art

![Screenshot from 2021-06-30 09-45-24](https://user-images.githubusercontent.com/58219504/123930880-09e95b80-d988-11eb-8dcb-65876a73afc1.png)

**Comment by marbetschar** [comment]
Indeed the basic algorithm in HyperTextView for scanning only changed parts of the whole text view can be further abstracted an is potentially useful for a lot of use cases (i.e. detecting flight numbers, calendar events, geo coordinates, ....).

However, doing spell checking is quite a different problem domain to detecting hyperlinks. While I do agree there might be cases where both things are useful in the same text field, I don't think we should add those statically.

Instead, we could potentially abstract the detection and handling logic using the [visitor pattern](https://en.wikipedia.org/wiki/Visitor_pattern) to make it more versatile.

**Comment by hanaral** [comment]
@marbetschar In that case it may be good to start by working on the backend logic like you suggested - which would be a good starting place to implement things like calendar events/times etc!

**Comment by marbetschar** [comment]
For future reference: I added a [feature request for "rule management" in a future GTK version](https://gitlab.gnome.org/GNOME/gtk/-/issues/3832#note_1195315) which would probably make said implementations easier.

**Comment by danrabbit** [comment]
I'm going to close as "Out of Scope" because spell checking, suggestions, autocomplete etc should really be tackled upstream in Gtk.Editable
