### ISSUE TITLE
Trying to access `prefers_color_scheme` fails at (flatpak) runtime.

### ISSUE THREAD

**Issue by dar5hak** [elementary/granite#512]
## What Happened

I was trying to add dark style support in my `Application.vala`, and added the following lines in `activate` method:

```vala
var granite_settings = Granite.Settings.get_default ();
var gtk_settings = Gtk.Settings.get_default ();

stdout.printf (@"\n$(granite_settings.prefers_color_scheme)");

gtk_settings.gtk_application_prefer_dark_theme = (
    granite_settings.prefers_color_scheme == Granite.Settings.ColorScheme.DARK
);

granite_settings.notify["prefers-color-scheme"].connect (() => {
    gtk_settings.gtk_application_prefer_dark_theme = (
        granite_settings.prefers_color_scheme == Granite.Settings.ColorScheme.DARK
    );
});
```

Building and running the app with meson and ninja works as expected. `flatpak-builder` builds without an issue. But when running the application using `flatpak run`, it crashes at the `printf` statement with the following output:

```
** (com.github.elfenware.badger:2): CRITICAL **: 19:15:31.315: Settings.vala:87: Could not connect: No such file or directory

** (com.github.elfenware.badger:2): CRITICAL **: 19:15:31.315: Settings.vala:109: Could not connect: No such file or directory
```

I believe `Settings.vala` refers to https://github.com/elementary/granite/blob/master/lib/Widgets/Settings.vala.

## Expected Behavior

Expected the app to run and follow the system colour scheme preference.

## Steps to Reproduce

1. `git clone git@github.com:elfenware/badger.git; cd badger`
2. `git checkout dark-style-support`
3. `flatpak-builder build com.github.elfenware.badger.yml --user --install --force-clean`
4. `flatpak run com.github.elfenware.badger`

### Logs

```
Gtk-Message: 19:36:12.479: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:36:12.486: Failed to load module "canberra-gtk-module"

💲️ Command line mode started
✔️ Activated

** (com.github.elfenware.badger:2): CRITICAL **: 19:36:12.493: Settings.vala:87: Could not connect: No such file or directory

** (com.github.elfenware.badger:2): CRITICAL **: 19:36:12.494: Settings.vala:109: Could not connect: No such file or directory
```
Is `canberra-gtk-module` relevant?

## Platform Information

Odin beta

**Comment by danrabbit** [comment]
In order to read the dark style preference, you need to add a sandbox hole for AccountsService where the setting is stored. You can add the following line to your `finish-args` for this:

`  - '--system-talk-name=org.freedesktop.Accounts'`

**Comment by danrabbit** [comment]
We should probably make sure to document this in Valadoc for this method

**Comment by dar5hak** [comment]
Thanks. I'll make a PR later today.
