### ISSUE TITLE
Scrolling while renaming an item in SourceList separates editable from renamed item

### ISSUE THREAD

**Issue by jeremypw** [elementary/granite#514]
## What Happened

If a Granite SourceList (e.g. the Code sidebar) is scrolled while renaming an item then the editable widget does not move but the item does.

Note that this is related to https://github.com/elementary/files/issues/1770 and may be due to an upstream bug.  A workround is to hide the scrollbar while renaming but this needs to be done within Granite SourceList as the required signal and widget are not exposed.

## Expected Behavior

Either scrolling is disabled (easier) or the editable scrolls in sync with the item

## Steps to Reproduce

1. Open a Code project with lots of files
2. Adjust the window size and expanded folders so that the sidebar becomes scrollable
3. Start to edit an item
4. Drag on the sidebar scrollbar.

## Platform Information

Elementary 6 daily

**Comment by danrabbit** [comment]
Closing since SourceList was removed during the Gtk4 port
