### ISSUE TITLE
Setting icon on existing WelcomeButton results in icon disappearing

### ISSUE THREAD

**Issue by aral** [elementary/granite#530]
### What Happened?

I set an icon on an existing `WelcomeButton`.

### Steps to Reproduce

1. Create a `WelcomeButton` instance
2. Change its icon (e.g., `myButton.icon = new Gtk.Image.from_icon_name ("process-completed", Gtk.IconSize.DIALOG);`)

### Expected Behavior

The icon should change.

## Actual bevavior

The icon disappears.

## Workaround

For the time being, I’m just recreating the whole `Welcome` view when the toggle state of a setting changes but that’s making the interface elements jump around so it’s not a long-term solution.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
No log output (warnings, etc.)
```

### Hardware Info

n/a

**Comment by aral** [comment]
Note on workaround: if you don’t want the interface to jump around, get a reference to one of the option buttons and request a width for it that you’re reasonably certain is longer than any of your localised buttons will naturally be.

e.g.,

```vala
int enable_disable_button_index;
            if (comet_is_enabled) {
                enable_disable_button_index = welcome.append ("comet-disable", _("Disable Comet"), _("Revert to using your previous editor for git commit messages."));
            } else {
                enable_disable_button_index = welcome.append ("comet-128", _("Enable Comet"), _("Use Comet as the default editor for git commit messages."));
            }
            enable_disable_button = welcome.get_button_from_index (enable_disable_button_index);

            // Request a specific width so the whole interface does not
            // jump around when we toggle it.
            enable_disable_button.width_request = 460;
```

**Comment by Antolius** [comment]
@aral You actually need to call `show_all` on the button after setting the new icon, like so:

```vala
var welcome = new Granite.Widgets.Welcome (
    "Granite Welcome Test App",
     "An app that explores updating WelcomeButton."
);

welcome.append ("view-refresh", "Change icon", "Change this button's icon!");
welcome.activated.connect ((index) => {
    var button = welcome.get_button_from_index (0);
    button.icon = new Gtk.Image.from_icon_name ("process-completed", Gtk.IconSize.DIALOG);
    button.show_all ();
});
```

I've created a minimal app that illustrates this: https://github.com/Antolius/granite-welcome-test

In GTK3 widgets are hidden by default after they are first created. In this case the `Gtk.Image` is created after the Welcome widget (and its buttons) were initially shown, so it remains invisible unless `show_all` is explicitly called again somewhere in its widget hierarchy.

**Comment by meisenzahl** [comment]
As @Antolius explained, all widgets behave this way under GTK3. With GTK4 this will change.

**Comment by aral** [comment]
@Antolius Thank you, I keep getting caught out by that.
