### ISSUE TITLE
Port or Remove Granite.SourceList

### ISSUE THREAD

**Issue by danrabbit** [elementary/granite#563]
It appears that only Code and Mail are using SourceList.

Photos, Files, and Tasks have their own custom treeview implementation or subclass ListBox.

We should decide if it's worth porting SourceList to GTK4, we want a new sidebar implementation, or apps should implement their own sidebars as needed

**Comment by meisenzahl** [comment]
Apparently some apps use this: https://github.com/search?l=Vala&q=Granite.Widgets.SourceList&type=Code

**Comment by Exalm** [comment]
I'd say it' worth to have a shared sidebar impl, and I'll be adding one in libadwaita in future.

What you should definitely do though is to port it away from treeview.
