### ISSUE TITLE
Remove BufferSurface

### ISSUE THREAD

**Issue by danrabbit** [elementary/granite#567]
This is used once in Photos: https://github.com/elementary/photos/blob/77a6b2eb0d847b6f6388e2e9924f3feb4f410195/src/Resources.vala#L264

But it's primarily used in Gala. Is this something we need in a GTK4 world with Gtk.CSS etc?

**Comment by meisenzahl** [comment]
Codecard uses this too: https://github.com/manexim/codecard/blob/01518f10faf634f2d8dd7878f1604e6a314c5577/src/MainWindow.vala#L274

But I guess that I could refactor the code.

**Comment by danrabbit** [comment]
It also seems like this is maybe superseded by Gtk.Drawing Area? https://valadoc.org/gtk4/Gtk.DrawingArea.html
