### ISSUE TITLE
Placeholder namespace conflicts with GTK?

### ISSUE THREAD

**Issue by cassidyjames** [elementary/granite#585]
I don't remember the exact details but I remember @danrabbit mentioning this. :sweat_smile: It might be able to be worked around in the stylesheet, but I think the simplest and clearest way forward to avoid collisions and just to better name it would be to rename our new widget something more clear and related to how we expect the pattern to be used. Does something like `Granite.EmptyState` make sense here?

**Comment by cassidyjames** [comment]
From @danrabbit:
>I'd rather not change the namespace of the widget itself because GTK uses `placeholder` as the property name for places we use this in list box etc
>
>It's the CSSName that conflicts with Gtk.Entry, so probably could change the css name to like `granite-placeholder` at worst

**Comment by danrabbit** [comment]
I think I'm just gonna leave it. It's not broken in Gtk default or in the elementary stylesheet
