### ISSUE TITLE
Switching tabs with `Alt` + number does not work when number is entered with keypad

### ISSUE THREAD

**Issue by jeremypw** [elementary/granite#590]
### What Happened?

It is possible to switch tabs using `Alt` + <number of tab> but this only works with the numbers generated by the keyboard.  Using the keypad does not work

### Steps to Reproduce

* Open two or more tabs in e.g. Terminal or Code
* Try to switch tabs using `Alt` + keyboard - it works
* Try to switch tabs using `Alt` + keypad - it does not work

### Expected Behavior

Both methods of entering a number should work.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Standard UK keyboard + keypad with gb locale.

**Comment by jeremypw** [comment]
Related to #76

**Comment by danrabbit** [comment]
Closing since DynamicNotebook was dropped in Granite 7
