### ISSUE TITLE
Packages fail to build agains granite on Artix

### ISSUE THREAD

**Issue by githubassets** [elementary/granite#625]
### What Happened?

Installing granite either from source, as per README, or from AUR does not provide `dependency('granite', version: '>=6.2.0')` and does not make 'Granite' class available on the system, which causes elementary/calendar to fail the build.

### Steps to Reproduce

1. Instal the required dependencies
2. Build the package by running `meson build --prefix=/usr; cd build; sudo ninja install`
3. Attempt to build elementary/calendar
`meson.build:26:0: ERROR: Dependency "granite" not found, tried pkgconfig and cmake`
4. Try to remove the dependency line from meson.build to proceed
`../src/Widgets/DeleteDialog.vala:1.36-1.42: error: The symbol `Granite' could not be found`

### Expected Behavior

It should compile as granite is installed

### OS Version

Other Linux

### Software Version

Compiled from git

**Comment by tintou** [comment]
I believe that you are building elementary Calendar, you need Granite < 7.0.0 for this as Granite 7 is the GTK4 version

**Comment by githubassets** [comment]
Installing granite 6.2. fixed the issue! Many thanks
