### ISSUE TITLE
../lib/Widgets/Settings.vala:9:52-9:61: error: `owned' accessor not allowed for specified property type

### ISSUE THREAD

**Issue by mcatanzaro** [elementary/granite#641]
### What Happened?

Since vala commit https://gitlab.gnome.org/GNOME/vala/-/commit/f8c0ce38c6954069a81561bff8207bf43a81c10f it's no longer possible to build Granite:

```
../lib/Widgets/Settings.vala:9:52-9:61: error: `owned' accessor not allowed for specified property type
    9 |         public abstract int prefers_color_scheme { owned get; set; }
      |                                                    ^~~~~~~~~~ 
```

It does not make sense for an int property to be owned since it's not heap-allocated.

### Steps to Reproduce

Try to build Granite

### Expected Behavior

Build should succeed

### OS Version

Other Linux

### Software Version

Compiled from git

**Comment by K4rakara** [comment]
Huge thanks for this, I was just cloning the repo to fix it myself, lol :+1:
