### ISSUE TITLE
../lib/Widgets/Utils.vala:267:38-267:40: error: Argument 1: Cannot convert from `unowned string' to `unowned uint8[]'

### ISSUE THREAD

**Issue by mcatanzaro** [elementary/granite#658]
### What Happened?

When building Granite git main using org.freedesktop.Sdk.Extension.vala-nightly:

```
../lib/Widgets/Utils.vala:267:38-267:40: error: Argument 1: Cannot convert from `unowned string' to `unowned uint8[]'
  267 |         css_provider.load_from_data (css);
      |                                      ^~~  
```

Lorenz pointed me to this corresponding vala issue: https://gitlab.gnome.org/GNOME/vala/-/issues/1478

It looks like we need to revert @alice-mkh's previous fix https://github.com/elementary/granite/commit/9065ac67831022bb9482f9405254a18924c7332d because the change in vala has been reverted.

### Steps to Reproduce

Build

### Expected Behavior

Failed to build

### OS Version

Other Linux

### Software Version

Compiled from git

**Comment by lw64** [comment]
I tested it and it indeed works with the latest valac from main with the commit reverted.
