### ISSUE TITLE
Provide a placeholder for listboxes

### ISSUE THREAD

**Issue by x421** [elementary/granite#66]
Just something I noticed while playing around:

I have an application with a listbox as one of the core widgets. But at the beginning this list will always be empty. I now created a stack with a new Granite.WelcomeScreen, but I have to take care of switching myself. And I doubt that the welcome screen has the right styling for this. At the point where the listbox is visible the user already had a welcome screen to open a file.

So what I am proposing is a Container based on Gtk.ListBox which allows me to add a placeholder headline and description.

Maybe a generic placeholder style can be made? I am thinking of something like the view of an empty folder in the files app.

**Comment by danrabbit** [comment]
Gtk.ListBox has a function to set a placeholder already: https://valadoc.org/gtk+-3.0/Gtk.ListBox.set_placeholder.html

I recommend using Granite.Widgets.AlertView with this: https://valadoc.org/granite/Granite.Widgets.AlertView.html
