### ISSUE TITLE
Rust bindings.

### ISSUE THREAD

**Issue by GreatC0der** [elementary/granite#661]
### Problem

Attract new developers, generation Z developers. Makes it easier to maintain apps because of Rust's architecture. 

 I would love to contribute though I don't have any skills for this.

### Proposal

I think that rust is perfectly suited for desktop apps because it's high level and fast. 

### Prior Art (Optional)

GTK supports rust.

**Comment by tintou** [comment]
Hi there, there are already bindings available https://lib.rs/crates/granite-rs

**Comment by GreatC0der** [comment]
Thank you. I apologise for disturbing you.
