### ISSUE TITLE
ModeButton can be untoggled

### ISSUE THREAD

**Issue by markodp** [elementary/granite#67]
If you click on mode that is selected then no mode is shown as active anymore. Sometimes this is wanted, but sometimes you need one of modes to be always on.

Some examples where this issue can be observed:
- view modes in Files
- Primary button section in Mouse & Touchpad settings

**Comment by markodp** [comment]
My suggestion would be to add new bool property that would:
- allow case for all modes being deselected, or
- enforce one mode to be always selected

**Comment by peteruithoven** [comment]
Example:
![snaptastic buttons](https://user-images.githubusercontent.com/523210/35806600-567aebe2-0a80-11e8-83af-f000f98aca5e.gif)

**Comment by fabiozaramella** [comment]
Since it's called ModeButton, it expresses a mode of being so it shouldn't be possible for a normal user to disable it, the only way to do it should be programmatically.
