### ISSUE TITLE
Add a duration property for Toasts

### ISSUE THREAD

**Issue by danrabbit** [elementary/granite#71]
It looks like [the Android implementation](https://developer.android.com/reference/android/widget/Toast.html#setDuration(int)) offers a property `duration`.

Gtk.Stack and Gtk.Revealer both offer a property `uint transition_duration`, so I think `duration` is a sane name.

The Android implementation also offers two constants:
```
LENGTH_LONG = 3500; // 3.5 seconds
LENGTH_SHORT = 2000; // 2 seconds
```

I'm not a fan of the names. It seems counter-intuitive to me to have `duration` be the property and then all the sudden the constant is `LENGTH_FOO`. Especially because I think "length" could also refer to physical dimensions so it's kind of an ambiguous name. So I would be in favor of maybe `DURATION_LONG` and `DURATION_SHORT`. In practice this would look like
```
var toast = new Granite.Widgets.Toast (_("This is a notification"));
toast.duration = Granite.Widgets.Toast.DURATION_SHORT;
```

Couple of open questions:
* Should the default duration still be infinity or should non-actionable Toasts disappear by default at some duration?
* Should the `duration` property be a `uint` like `Gtk.Foo.transition_duration` or should it be an `enum` like on Android? (ie no custom durations, only a choice between predefined durations)

**Comment by lainsce** [comment]
My $0.02:
I think the default duration should be at least 6 seconds. With a code switch to make it non-disappear-able.
And for simplicity sake an uint should be more than enough.

**Comment by donadigo** [comment]
I think the API design should resamble the rules used in e.g: Gtk.Stack.

So regarding the first question:
The default duration should be whatever the default duration actually is (so no `-1`). For that a `DURATION_DEFAULT` should be used and declared for public API or other you've mentioned like `_SHORT` or `_LONG`. Keep in mind that `-1` also isn't a valid number within `uint` type.

The second question:
Developers should be able to set whatever duration they want, and hence, enums cannot be used for that. A `uint` is a sane type for this kind of property. What @lainsce also said is that, there could be a switch for making the toast stay forever. This could be easily achevied by e.g: using values for `duration` like `0` or `uint.MAX`.

**Comment by danrabbit** [comment]
By `-1` I just meant infinite

**Comment by danrabbit** [comment]
Aright, so some quick discussion in #ux lead to the conclusion that Toasts should always time out. Even actionable toasts. If you want infinite duration, use an infobar.

non-actionable toasts should default to `DURATION_SHORT` and actionable toasts should default to `DURATION_LONG`
