### ISSUE TITLE
Control + Page Up/Down should switch tabs (or move with additional Shift)

### ISSUE THREAD

**Issue by cassidyjames** [elementary/granite#76]
From https://github.com/elementary/terminal/issues/2

**Comment by janxkoci** [comment]
In all other terminal apps that I know of (e.g. gnome-terminal, terminator or tilix) it's Ctrl+Page Up/Down to switch tabs (and with additional shift to move tabs) - and this is actually the case in most other apps, like browsers, nautilus, sublime-text, etc. It's a standard behaviour.

**Comment by danrabbit** [comment]
Closing since we removed DynamicNotebook in favor of Hdy.Tabbar
