### ISSUE TITLE
Create a relative date time function

### ISSUE THREAD

**Issue by btkostner** [elementary/granite#91]
We use relative date time logic in a lot of places. We should consolidate the logic into a method of `Granite.DateTime`.

This would replace the logic for:
- [Mail](https://github.com/elementary/mail/blob/rewrite/src/ConversationList/ConversationListItem.vala#L118)
- [Notification indicator](https://github.com/elementary/wingpanel-indicator-notifications/blob/master/src/Widgets/NotificationEntry.vala#L114)
- Some other third party apps like vocal.

**Comment by matzipan** [comment]
I also have a [class](https://github.com/matzipan/envoyer/blob/47f7b826f2644eba93710ec9eb882dc9047ef3a4/src/FutureGranite/HumanDateTime.vala) and a [test](https://github.com/matzipan/envoyer/blob/47f7b826f2644eba93710ec9eb882dc9047ef3a4/src/FutureGranite/tests/HumanDateTimeTest.vala)
