### ISSUE TITLE
Middle-click close tab should cancel if the button release is not over the tab widget

### ISSUE THREAD

**Issue by cassidyjames** [elementary/granite#95]
Similar to but distinct from #82. Middle-clicking to close a tab should only work when both the press _and_ release even occur with the cursor over the tab.

 On my machine (with a physical mouse, not a trackpad), it appears that middle-clicking a tab, dragging the cursor away from the tab, then releasing the middle-click still closes the tab. Instead, middle-click, drag, and release should not close the tab since the release is not occurring on the tab widget.

**Comment by danrabbit** [comment]
Using a trackpad on Artful. It seems like there is some kind of race condition. If I perform the action within about 300-500ms it will still close, but otherwise seems to work as expected.

**Comment by danrabbit** [comment]
Closing since we removed DynamicNotebook in favor of Hdy.Tabbar
